/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class io_xjar_XJni */

#ifndef _Included_io_xjar_XJni
#define _Included_io_xjar_XJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_xjar_XJni
 * Method:    call
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_xjar_XJni_call(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
